.. _calpendo: https://campusbiotech.calpendo.com/
.. _lab streaming layer: https://labstreaminglayer.org/
.. _liblsl repo: https://github.com/sccn/liblsl
.. _LRPA: https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/
.. _lsl meta repo: https://github.com/sccn/labstreaminglayer/tree/master/LSL
.. _lsl neta repo apps: https://github.com/sccn/labstreaminglayer/tree/master/Apps
.. _mne stable: https://mne.tools/stable/index.html
.. _mne standalone installers: https://mne.tools/stable/install/installers.html
.. _mne-lsl: https://mne.tools/mne-lsl/stable/index.html
.. _Nasion: https://en.wikipedia.org/wiki/Nasion
.. _pre-commit: https://pre-commit.com/
.. _project github doc: https://github.com/fcbg-platforms/eeg-wiki/tree/main/doc
.. _project github: https://github.com/fcbg-platforms/eeg-wiki
.. _project issue tracker: https://github.com/fcbg-platforms/eeg-wiki/issues
.. _project license: https://github.com/fcbg-platforms/eeg-wiki/blob/main/LICENSE
.. _psychopy: https://www.psychopy.org/
.. _psychtoolbox: http://psychtoolbox.org/
.. _pylsl: https://github.com/labstreaminglayer/pylsl/tree/21fbbc30811fe151992654cdc5fa62a9a0f4d0be
.. _rst: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
.. _sphinx-gallery: https://sphinx-gallery.github.io/stable/index.html
.. _XT-20000QC3: https://xtpower.de/XT-20000QC3/
