.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. glossary

.. _LRPA: https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/
.. _Nasion: https://en.wikipedia.org/wiki/Nasion
.. _rst: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html


.. others

.. _calpendo: https://campusbiotech.calpendo.com/


.. project

.. _project github: https://github.com/fcbg-hnp-meeg/eeg-wiki
.. _project github doc: https://github.com/fcbg-hnp-meeg/eeg-wiki/tree/main/doc
.. _project issue tracker: https://github.com/fcbg-hnp-meeg/eeg-wiki/issues
.. _project license: https://github.com/fcbg-hnp-meeg/eeg-wiki/blob/main/LICENSE


.. software

.. _mne stable: https://mne.tools/stable/index.html
.. _pre-commit: https://pre-commit.com/
.. _psychopy: https://www.psychopy.org/
.. _psychtoolbox: http://psychtoolbox.org/
.. _sphinx-gallery: https://sphinx-gallery.github.io/stable/index.html
